# Regresión Lineal Múltiple


# Cómo importar las librerías


In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importar el data set


In [3]:
dataset = pd.read_csv('50_Startups.csv')

In [4]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [5]:
X = dataset.iloc[:, :-1].values
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [6]:
y = dataset.iloc[:, 4].values
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

# Codificar datos categóricos

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import make_column_transformer

In [8]:
labelencoder_X = LabelEncoder()

In [9]:
X[:, 3] = labelencoder_X.fit_transform(X[:, 3])

In [10]:
X

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 1],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 1],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 1],
       [100671.96, 91790.61, 249744.55, 0],
       [93863.75, 127320.38, 249839.44, 1],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 1],
       [86419.7, 153514.11, 0.0, 2],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 30331

In [11]:
onehotencoder = make_column_transformer((OneHotEncoder(), [3]), remainder = "passthrough")

In [12]:
X = onehotencoder.fit_transform(X)
X

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

# Evitar la trampa de las variables ficticias


In [13]:
X = X[:, 1:]

In [14]:
X

array([[0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [0.0, 1.0, 86419.7

# Dividir el data set en conjunto de entrenamiento y conjunto de testing


In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Escalado de variables

In [157]:
"""
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
"""

'\nfrom sklearn.preprocessing import StandardScaler\nsc_X = StandardScaler()\nX_train = sc_X.fit_transform(X_train)\nX_test = sc_X.transform(X_test)\n'

# Ajustar el modelo de Regresión lineal múltiple con el conjunto de entrenamiento


In [158]:
from sklearn.linear_model import LinearRegression

In [159]:
regression = LinearRegression()
regression.fit(X_train, y_train)

LinearRegression()

In [160]:
regression.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'normalize': False}

# Predicción de los resultados en el conjunto de testing


In [161]:
y_pred = regression.predict(X_test)

In [162]:
y_pred

array([103015.20159796, 132582.27760815, 132447.73845175,  71976.09851258,
       178537.48221056, 116161.24230166,  67851.69209676,  98791.73374687,
       113969.43533013, 167921.06569551])

In [163]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [164]:
pd.DataFrame({"prediccion":y_pred, "realidad":y_test})

prediccion   realidad
0  103015.201598  103282.38
1  132582.277608  144259.40
2  132447.738452  146121.95
3   71976.098513   77798.83
4  178537.482211  191050.39
5  116161.242302  105008.31
6   67851.692097   81229.06
7   98791.733747   97483.56
8  113969.435330  110352.25
9  167921.065696  166187.94

# Construir el modelo óptimo de RLM utilizando la Eliminación hacia atrás

In [165]:
import statsmodels.api as sm
# agregamos una columna con 1 y la asociamos al coeficioente del termino independiente
# debe estar al principio del datasets
X  = np.append(arr = np.ones((50,1)).astype(int), values = X, axis = 1)
X

array([[1, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [1, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [1, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [1, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [1, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [1, 0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1, 1.0, 0.0, 9

Se ha añadido el modificador .tolist() al X_opt para adaptarse a Python 3.7

In [166]:
SL = 0.05
X_opt = X[:, [0, 1, 2, 3, 4, 5]]
regression_OLS = sm.OLS(endog = y, exog = X_opt.tolist()).fit()

In [167]:
print(dir(regression_OLS))

['HC0_se', 'HC1_se', 'HC2_se', 'HC3_se', '_HCCM', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abat_diagonal', '_cache', '_data_attr', '_data_in_cache', '_get_robustcov_results', '_is_nested', '_use_t', '_wexog_singular_values', 'aic', 'bic', 'bse', 'centered_tss', 'compare_f_test', 'compare_lm_test', 'compare_lr_test', 'condition_number', 'conf_int', 'conf_int_el', 'cov_HC0', 'cov_HC1', 'cov_HC2', 'cov_HC3', 'cov_kwds', 'cov_params', 'cov_type', 'df_model', 'df_resid', 'eigenvals', 'el_test', 'ess', 'f_pvalue', 'f_test', 'fittedvalues', 'fvalue', 'get_influence', 'get_prediction', 'get_robustcov_results', 'initialize', 'k_constant', 'llf', 'load', 'model', 'mse_model', 'mse_resid', 'mse_to

In [168]:
print(regression_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Sat, 24 Apr 2021   Prob (F-statistic):           1.34e-27
Time:                        21:09:18   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.0

In [169]:
regression_OLS.pvalues.argmax()

2

In [170]:
regression_OLS.rsquared, regression_OLS.rsquared_adj

(0.9507524843355148, 0.945156175737278)

segun los resultados el pvalor mas alto corresponde a la variable de la columna con indice 2 y se 
eliminara para el proximo paso

In [171]:
X_opt = X[:, [0, 1, 3, 4, 5]]
regression_OLS = sm.OLS(endog = y, exog = X_opt.tolist()).fit()
regression_OLS.summary()
if any(x>SL for x in regression_OLS.pvalues):
    print("hay variables para eliminar")
    print("la variable a eliminar es la columna :",regression_OLS.pvalues.argmax())
else:
    print("ya llegamos a obtener las variables que mejor van para el modelo")
    print("los datos para el modelo son:")
    display(X_opt)

hay variables para eliminar
la variable a eliminar es la columna : 1


In [172]:
regression_OLS.pvalues.argmax()

1

segun los resultados el pvalor mas alto corresponde a la variable de la columna con indice 1 y se 
eliminara para el proximo paso

In [173]:
X_opt = X[:, [0, 3, 4, 5]]
regression_OLS = sm.OLS(endog = y, exog = X_opt.tolist()).fit()
print(regression_OLS.summary())
if any(x>SL for x in regression_OLS.pvalues):
    print("hay variables para eliminar")
    print("la variable a eliminar es la columna :",regression_OLS.pvalues.argmax())
else:
    print("ya llegamos a obtener las variables que mejor van para el modelo")
    print("los datos para el modelo son:")
    display(X_opt)

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Sat, 24 Apr 2021   Prob (F-statistic):           4.53e-30
Time:                        21:09:23   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.0

In [174]:
X_opt = X[:, [0, 3, 5]]
regression_OLS = sm.OLS(endog = y, exog = X_opt.tolist()).fit()
print(regression_OLS.summary())
if any(x>SL for x in regression_OLS.pvalues):
    print("hay variables para eliminar")
    print("la variable a eliminar es la columna :",regression_OLS.pvalues.argmax())
else:
    print("ya llegamos a obtener las variables que mejor van para el modelo")
    print("los datos para el modelo son:")
    display(X_opt)

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Sat, 24 Apr 2021   Prob (F-statistic):           2.16e-31
Time:                        21:09:24   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.0

In [176]:
X_opt = X[:, [0, 3]]
regression_OLS = sm.OLS(endog = y, exog = X_opt.tolist()).fit()
regression_OLS.summary()
if any(x>SL for x in regression_OLS.pvalues):
    print("hay variables para eliminar")
    print("la variable a eliminar es la columna :",regression_OLS.pvalues.argmax())
else:
    print("ya llegamos a obtener las variables que mejor van para el modelo")
    print("los datos para el modelo son:")
    display(X_opt)

ya llegamos a obtener las variables que mejor van para el modelo
los datos para el modelo son:


array([[1, 165349.2],
       [1, 162597.7],
       [1, 153441.51],
       [1, 144372.41],
       [1, 142107.34],
       [1, 131876.9],
       [1, 134615.46],
       [1, 130298.13],
       [1, 120542.52],
       [1, 123334.88],
       [1, 101913.08],
       [1, 100671.96],
       [1, 93863.75],
       [1, 91992.39],
       [1, 119943.24],
       [1, 114523.61],
       [1, 78013.11],
       [1, 94657.16],
       [1, 91749.16],
       [1, 86419.7],
       [1, 76253.86],
       [1, 78389.47],
       [1, 73994.56],
       [1, 67532.53],
       [1, 77044.01],
       [1, 64664.71],
       [1, 75328.87],
       [1, 72107.6],
       [1, 66051.52],
       [1, 65605.48],
       [1, 61994.48],
       [1, 61136.38],
       [1, 63408.86],
       [1, 55493.95],
       [1, 46426.07],
       [1, 46014.02],
       [1, 28663.76],
       [1, 44069.95],
       [1, 20229.59],
       [1, 38558.51],
       [1, 28754.33],
       [1, 27892.92],
       [1, 23640.93],
       [1, 15505.73],
       [1, 22177.74],
 

No eliminamos mas por que las dos variables que quedaron superan el valor de SL 

# Eliminación hacia atrás utilizando solamente p-valores:

In [39]:
import statsmodels.api as sm
import numpy as np
import pandas as pd

In [40]:
dataset = pd.read_csv('50_Startups.csv')
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [65]:
X = pd.get_dummies(dataset,columns=["State"], drop_first=True,prefix=["0"]).drop(columns=["Profit"])
display(X.head())
X = pd.DataFrame(X, columns=sorted(X.columns))
display(X.head())
X = X.to_numpy()
display(X[:5,:])
X = np.append(arr = np.ones((50,1)).astype(int), values = X, axis = 1)
X[:5,:]

R&D Spend  Administration  Marketing Spend  0_Florida  0_New York
0  165349.20       136897.80        471784.10          0           1
1  162597.70       151377.59        443898.53          0           0
2  153441.51       101145.55        407934.54          1           0
3  144372.41       118671.85        383199.62          0           1
4  142107.34        91391.77        366168.42          1           0

0_Florida  0_New York  Administration  Marketing Spend  R&D Spend
0          0           1       136897.80        471784.10  165349.20
1          0           0       151377.59        443898.53  162597.70
2          1           0       101145.55        407934.54  153441.51
3          0           1       118671.85        383199.62  144372.41
4          1           0        91391.77        366168.42  142107.34

array([[0.0000000e+00, 1.0000000e+00, 1.3689780e+05, 4.7178410e+05,
        1.6534920e+05],
       [0.0000000e+00, 0.0000000e+00, 1.5137759e+05, 4.4389853e+05,
        1.6259770e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0114555e+05, 4.0793454e+05,
        1.5344151e+05],
       [0.0000000e+00, 1.0000000e+00, 1.1867185e+05, 3.8319962e+05,
        1.4437241e+05],
       [1.0000000e+00, 0.0000000e+00, 9.1391770e+04, 3.6616842e+05,
        1.4210734e+05]])

array([[1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3689780e+05,
        4.7178410e+05, 1.6534920e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.5137759e+05,
        4.4389853e+05, 1.6259770e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.0114555e+05,
        4.0793454e+05, 1.5344151e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.1867185e+05,
        3.8319962e+05, 1.4437241e+05],
       [1.0000000e+00, 1.0000000e+00, 0.0000000e+00, 9.1391770e+04,
        3.6616842e+05, 1.4210734e+05]])

In [66]:
y=dataset["Profit"]
y[:5]

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [48]:
def backwardElimination(x, sl):    
    numVars = len(x[0])    
    for i in range(0, numVars):        
        regressor_OLS = sm.OLS(y, x.tolist()).fit()        
        maxVar = max(regressor_OLS.pvalues) #.astype(float)        
        if maxVar > sl:            
            for j in range(0, numVars - i):                
                if (regressor_OLS.pvalues[j] == maxVar):     #.astype(float) == maxVar):                    
                    x = np.delete(x, j, 1)    
    print(regressor_OLS.summary())    
    return x 

El código proporcionado implementa un algoritmo de eliminación hacia atrás para seleccionar las variables más significativas en un modelo de regresión lineal. 

El algoritmo toma dos parámetros: "x", que es una matriz de características independientes, y "sl", que es el nivel de significancia (p-value) máximo permitido. El objetivo del algoritmo es eliminar las variables que tienen un p-value mayor que el nivel de significancia dado.

El código comienza obteniendo el número de variables en la matriz "x" y luego inicia un bucle que itera sobre todas las variables. Dentro del bucle, se ajusta un modelo de regresión lineal utilizando la función OLS de la biblioteca "sm" y se guarda en la variable "regressor_OLS".

A continuación, se determina la variable con el p-value máximo utilizando la función "max" en la lista de p-values del modelo ajustado. Si este valor máximo es mayor que el nivel de significancia dado, se inicia otro bucle que itera sobre las variables restantes.

Dentro de este segundo bucle, se verifica si el p-value de cada variable es igual al valor máximo encontrado anteriormente. Si es así, se elimina esa variable de la matriz "x" utilizando la función "np.delete".

Después de que el bucle principal se completa, se imprime el resumen del modelo ajustado final utilizando la función "summary" de la variable "regressor_OLS". Finalmente, se devuelve la matriz "x" modificada, que ahora contiene solo las variables más significativas según el criterio de eliminación hacia atrás.

En resumen, el código implementa un algoritmo de eliminación hacia atrás para seleccionar las variables más significativas en un modelo de regresión lineal y devuelve la matriz de características independientes modificada.

### que es p.value?

El p-value (valor p) es una medida estadística utilizada en pruebas de hipótesis para evaluar la evidencia en contra de una hipótesis nula. En el contexto de la regresión lineal, el p-value se utiliza para determinar la significancia estadística de los coeficientes de las variables independientes.

En términos generales, el p-value indica la probabilidad de obtener un resultado igual o más extremo que el observado, asumiendo que la hipótesis nula es cierta. Si el p-value es menor que un nivel de significancia predefinido (generalmente 0.05 o 0.01), se considera que hay suficiente evidencia para rechazar la hipótesis nula y concluir que el coeficiente de la variable independiente es significativamente diferente de cero.

En el contexto de la eliminación hacia atrás en el código que proporcionaste, se utiliza el p-value para determinar qué variables deben eliminarse del modelo de regresión lineal. Si el p-value de una variable es mayor que el nivel de significancia dado (sl), se considera que esa variable no es estadísticamente significativa y se elimina del modelo.

In [49]:
SL = 0.05
X_opt = X[:, [0, 1, 2, 3, 4, 5]]
X_Modeled = backwardElimination(X_opt, SL)

                            OLS Regression Results                            
Dep. Variable:                 Profit   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Sun, 25 Apr 2021   Prob (F-statistic):           3.50e-32
Time:                        10:39:47   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.0

In [47]:
X_Modeled

array([[1.0000000e+00, 1.6534920e+05],
       [1.0000000e+00, 1.6259770e+05],
       [1.0000000e+00, 1.5344151e+05],
       [1.0000000e+00, 1.4437241e+05],
       [1.0000000e+00, 1.4210734e+05],
       [1.0000000e+00, 1.3187690e+05],
       [1.0000000e+00, 1.3461546e+05],
       [1.0000000e+00, 1.3029813e+05],
       [1.0000000e+00, 1.2054252e+05],
       [1.0000000e+00, 1.2333488e+05],
       [1.0000000e+00, 1.0191308e+05],
       [1.0000000e+00, 1.0067196e+05],
       [1.0000000e+00, 9.3863750e+04],
       [1.0000000e+00, 9.1992390e+04],
       [1.0000000e+00, 1.1994324e+05],
       [1.0000000e+00, 1.1452361e+05],
       [1.0000000e+00, 7.8013110e+04],
       [1.0000000e+00, 9.4657160e+04],
       [1.0000000e+00, 9.1749160e+04],
       [1.0000000e+00, 8.6419700e+04],
       [1.0000000e+00, 7.6253860e+04],
       [1.0000000e+00, 7.8389470e+04],
       [1.0000000e+00, 7.3994560e+04],
       [1.0000000e+00, 6.7532530e+04],
       [1.0000000e+00, 7.7044010e+04],
       [1.0000000e+00, 6.

# Eliminación hacia atrás utilizando  p-valores y el valor de  R Cuadrado Ajustado:

## que es el R Cuadrado Ajustaso:

El valor de R cuadrado ajustado (R-squared ajustado) es una medida utilizada para evaluar la calidad de ajuste de un modelo de regresión. Es similar al valor de R cuadrado (R-squared), pero tiene en cuenta el número de variables independientes en el modelo y penaliza el valor de R cuadrado por la inclusión de variables irrelevantes.

El R cuadrado ajustado se calcula utilizando la siguiente fórmula:

R-cuadrado ajustado = 1 - [(1 - R-cuadrado) * (n - 1) / (n - k - 1)]

Donde:
- R-cuadrado es el valor de R cuadrado del modelo (que indica la proporción de la variabilidad de la variable dependiente explicada por las variables independientes).
- n es el número de observaciones en el conjunto de datos.
- k es el número de variables independientes en el modelo.

El R cuadrado ajustado toma valores entre 0 y 1. Un valor más cercano a 1 indica un mejor ajuste del modelo, teniendo en cuenta el número de variables independientes. Se prefiere un R cuadrado ajustado más alto, ya que indica que una mayor proporción de la variabilidad de la variable dependiente es explicada por las variables independientes relevantes en el modelo.

In [56]:
def backwardElimination(x, SL):    
    numVars = len(x[0])    
    temp    = np.zeros((50,6)).astype(int)    
    for i in range(0, numVars):        
        regressor_OLS = sm.OLS(y, x.tolist()).fit()        
        maxVar        = max(regressor_OLS.pvalues)      #.astype(float)        
        adjR_before   = regressor_OLS.rsquared_adj      # .astype(float)        
        if maxVar > SL:            
            for j in range(0, numVars - i):                
                if (regressor_OLS.pvalues[j] == maxVar): #astype(float)                    
                    temp[:,j]     = x[:, j]                    
                    x             = np.delete(x, j, 1)                    
                    tmp_regressor = sm.OLS(y, x.tolist()).fit()                    
                    adjR_after    = tmp_regressor.rsquared_adj  # .astype(float)                    
                    if (adjR_before >= adjR_after):                        
                        x_rollback = np.hstack((x, temp[:,[0,j]]))                        
                        x_rollback = np.delete(x_rollback, j, 1)     
                        print (regressor_OLS.summary())                        
                        return x_rollback                    
                    else:                        
                        continue    
    #print(regressor_OLS.summary())    
    return x 

In [57]:
SL = 0.05
X_opt = X[:, [0, 1, 2, 3, 4, 5]]
X_Modeled = backwardElimination(X_opt, SL)

                            OLS Regression Results                            
Dep. Variable:                 Profit   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Sun, 25 Apr 2021   Prob (F-statistic):           2.16e-31
Time:                        10:46:51   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.0

In [55]:
X_Modeled

array([[1.00000e+00, 0.00000e+00, 4.71784e+05],
       [1.00000e+00, 0.00000e+00, 4.43898e+05],
       [1.00000e+00, 0.00000e+00, 4.07934e+05],
       [1.00000e+00, 0.00000e+00, 3.83199e+05],
       [1.00000e+00, 0.00000e+00, 3.66168e+05],
       [1.00000e+00, 0.00000e+00, 3.62861e+05],
       [1.00000e+00, 0.00000e+00, 1.27716e+05],
       [1.00000e+00, 0.00000e+00, 3.23876e+05],
       [1.00000e+00, 0.00000e+00, 3.11613e+05],
       [1.00000e+00, 0.00000e+00, 3.04981e+05],
       [1.00000e+00, 0.00000e+00, 2.29160e+05],
       [1.00000e+00, 0.00000e+00, 2.49744e+05],
       [1.00000e+00, 0.00000e+00, 2.49839e+05],
       [1.00000e+00, 0.00000e+00, 2.52664e+05],
       [1.00000e+00, 0.00000e+00, 2.56512e+05],
       [1.00000e+00, 0.00000e+00, 2.61776e+05],
       [1.00000e+00, 0.00000e+00, 2.64346e+05],
       [1.00000e+00, 0.00000e+00, 2.82574e+05],
       [1.00000e+00, 0.00000e+00, 2.94919e+05],
       [1.00000e+00, 0.00000e+00, 0.00000e+00],
       [1.00000e+00, 0.00000e+00, 2.9866